"""is_deleted field added in todo models

Revision ID: ca6618db2b36
Revises: eb57c4b33033
Create Date: 2025-04-10 11:55:02.780282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca6618db2b36'
down_revision: Union[str, None] = 'eb57c4b33033'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.drop_column('todo', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('category', sa.VARCHAR(), nullable=True))
    op.drop_column('todo', 'is_deleted')
    # ### end Alembic commands ###
